### ISSUE TITLE
Serial communication (UART, SPI, I2C...)

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/KORUZA-router#8]
Serial ports:
- UART is required for communication with the driver board (stepper motors, ir_link, laser...), also it is useful for serial console (debugging) of the router board
- I2C is necessary because there is communication with SFP modules
- SPI is not that important, but it is good to have on some kind of expansion connector for some further upgrades.

**Comment by SloMusti** [comment]
Due to two SFP ports on the board, I2C multiplexing is required.
